services:
  app:
    build:
      context: ../
      dockerfile: ./deploy/dockerfile.dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file: ../.env
    command: [ "uvicorn", "mrkr:app", "--host", "0.0.0.0", "--port", "${APP_PORT}" ]
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 2s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - logs:/var/logs
  database:
    hostname: database
    image: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/${POSTGRES_DATABASE}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file: ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    extra_hosts:
      - "${POSTGRES_USER}:${POSTGRES_EXTRA_HOST}"

volumes:
  postgres-data:
  logs:
